### ISSUE TITLE
issue: environment variable not working

### ISSUE THREAD

**Issue by lukepighetti** [leancodepl/arb_translate#13]
<img width="629" alt="Screenshot 2024-06-20 at 7 51 10 AM" src="https://github.com/leancodepl/arb_translate/assets/666539/8ec653b4-ea22-47d4-b1df-dddd62990a3f">

https://x.com/luke_pighetti/status/1803751137574568131

**Comment by RobertOdrowaz** [comment]
@lukepighetti Are you sure you've exported the env var? This seems like the only way I'm able to reproduce the case of `arb_translate` not working and `arb_translate --api-key=$...` working correctly
![image](https://github.com/leancodepl/arb_translate/assets/9675199/e42dd120-7e68-4d7a-93e1-ce795f6073c7)

**Comment by RobertOdrowaz** [comment]
@lukepighetti I'm closing this issue under the assumption that it was a missing export. Let me know if you confirm it wasn't it
