### ISSUE TITLE
add arb_translation with last version

### ISSUE THREAD

**Issue by Moatasem159** [leancodepl/arb_translate#2]
Hi leanCode team,

thanks for this package
 
so i want to add arb_translation with last version and this happen:

Note: meta is pinned to version 1.11.0 by flutter from the flutter SDK.
See https://dart.dev/go/sdk-version-pinning for details.

Because arb_translate >=0.0.2 depends on meta ^1.12.0 and every version of flutter from sdk depends on meta 1.11.0, arb_translate >=0.0.2 is incompatible with flutter from sdk.
So, because test_translate depends on both flutter from sdk and arb_translate ^0.1.0, version solving failed.

You can try the following suggestion to make the pubspec resolve:
* Consider downgrading your constraint on arb_translate: flutter pub add arb_translate:^0.0.1.

this is my flutter doctor:
[√] Flutter (Channel stable, 3.19.0, on Microsoft Windows [Version 10.0.19045.3996], locale en-US)
    • Flutter version 3.19.0 on channel stable at C:\dev\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision bae5e49bc2 (3 days ago), 2024-02-13 17:46:18 -0800
    • Engine revision 04817c99c9
    • Dart version 3.3.0
    • DevTools version 2.31.1
    • Pub download mirror https://pub-web.flutter-io.cn/

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at C:\Users\moata\AppData\Local\Android\Sdk
    • Platform android-33-ext4, build-tools 33.0.1
    • Java binary at: C:\Program Files\Android\Android Studio1\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.5.3)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.5.33516.290
    • Windows 10 SDK version 10.0.22000.0

[√] Android Studio (version 2023.1)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)

[√] VS Code (version 1.86.1)
    • VS Code at C:\Users\moata\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19045.3996]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 121.0.6167.184
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 121.0.2277.112

[√] Network resources
    • All expected network resources are available.

• No issues found!
Process finished with exit code 0
Thanks in advance for your help !

**Comment by RobertOdrowaz** [comment]
Hi,
I assume you want to add `arb_translate` as a dependency in `pubspec.yaml`, right? This isn't currently supported. `arb_translate` is intended to be used as a global tool so you don't need to add it to `pubspec.yaml` just enable it by running:
```
dart pub global activate arb_translate
```

**Comment by Moatasem159** [comment]
Great thanks 🫡
