### ISSUE TITLE
Issue with Nested JSON Structure Translation

### ISSUE THREAD

**Issue by tejaswini-dev-techie** [leancodepl/arb_translate#6]
The arb_translate encounters difficulties when attempting to translate the below-mentioned nested JSON structures, leading to translation failures in certain cases.

JSON Format

```
{
    "title": "Home",
    "description": "Welcome to our app! Explore and enjoy your experience.",
    "homeButton": "Go to the home page 🎉",
    "logout_screen": {
        "logout_title": "Logout",
        "logout_subtitle": "Are you sure you want to Logout?"
    }
}
```

Translation Failed

<img width="425" alt="Screenshot 2024-02-25 at 8 20 32 PM" src="https://github.com/leancodepl/arb_translate/assets/79466038/febb8577-c3ff-45be-8cc2-f4074fdd5b5e">

**Comment by RobertOdrowaz** [comment]
Nesting isn't allowed in ARB format (at least in `flutter_localizations`) so it's not supported by `arb_translate`. I think you can modify the code a bit to work correctly with nesting but our priority is generating valid ARB files so we are not planning to support this.
![Screenshot from 2024-02-25 19-21-26](https://github.com/leancodepl/arb_translate/assets/9675199/ba38b653-4977-40cf-a023-bac547f9b5a2)
