### ISSUE TITLE
Exclude locales

### ISSUE THREAD

**Issue by dumazy** [leancodepl/arb_translate#8]
Hi,

Is it possible to exclude certain locales? Just as mentioned in [this issue](https://github.com/leancodepl/arb_translate/issues/5), not all languages are supported by the underlying model.
Specifically, I'm having issues with Albanian `sq` and the Vertex model, but would be happy to just be able to exclude this from `arb_translate` for now, without having to delete the `.arb` file from the directory.

**Comment by RobertOdrowaz** [comment]
I've added option to exclude locales in the new version (0.1.3). You can use `--exclude-locales sq,es` command line param or `arb-translate-exclude-locales: ["sq", "es"]` option in `l10n.yaml`
